vsphere_env: &vsphere_env
  GOVC_INSECURE: ((GOVC.INSECURE))
  GOVC_PASSWORD: ((GOVC.PASSWORD))
  GOVC_URL: ((GOVC.URL))
  GOVC_USERNAME: ((GOVC.USERNAME))
  GOVC_RESOURCE_POOL: ((GOVC.RESOURCE_POOL))
  GOVC_DATASTORE: ((GOVC.DATASTORE)) 
  GOVC_DATACENTER: ((GOVC.DATACENTER)) 
  GOVC_NETWORK: ((GOVC.NETWORK))
  LABBUILDR_RESOURCE_POOL: ((LABBUILDR.LAB1.RESOURCE_POOL))
  LABBUILDR_DATASTORE: ((LABBUILDR.LAB1.DATASTORE)) 
  LABBUILDR_DATACENTER: ((LABBUILDR.LAB1.DATACENTER))
  LABBUILDR_NETWORK: ((LABBUILDR.LAB1.NETWORK))
  LABBUILDR_SUBNET: ((LABBUILDR.LAB1.SUBNET))
  LABBUILDR_GATEWAY: ((LABBUILDR.LAB1.GATEWAY))
  LABBUILDR_NETMASK: ((LABBUILDR.LAB1.NETMASK))
  LABBUILDR_FQDN: ((LABBUILDR.LAB1.FQDN))
  LABBUILDR_DNS: ((LABBUILDR.LAB1.DNS))
  LABBUILDR_VM_FOLDER: ((LABBUILDR.LAB1.VM_FOLDER))
  LABBUILDR_TIMEZONE: ((LABBUILDR.LAB1.TIMEZONE))
  LABBUILDR_LANGUAGE_TAG: ((LABBUILDR.LAB1.LANGUAGE_TAG))
  LABBUILDR_LOGINUSER: ((LABBUILDR.LAB1.WINDOWS_LOGINUSER))
  LABBUILDR_DEBUG: ((LABBUILDR.LAB1.DEBUG))


  
s3_env: &s3_env
  access_key_id: ((((foundation))/s3_access_key_id))
  endpoint:  ((((foundation))/s3_endpoint))
  region_name: ((((foundation))/s3_region_name))
  secret_access_key: ((((foundation))/s3_secret_access_key))

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
   
resources:
- name: one-time-trigger
  icon: calendar-clock
  tags: ((tags))      
  type: time
  source:
    interval: 999999h
- name: dps-automation-image
  icon: docker
  type: docker-image
  source:
    repository: harbor.pks.home.labbuildr.com/bottkars/dps-automation-image
    ca_certs:
    - domain: harbor.pks.home.labbuildr.com
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
        MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
        DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
        SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
        GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
        AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
        q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
        SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
        Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
        a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
        /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
        AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
        CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
        bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
        c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
        VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
        ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
        MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
        Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
        AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
        uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
        wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
        X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
        PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
        KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
        -----END CERTIFICATE-----  
    tag: 0.3.12


- name: labbuildr-scripts
  tags: ((tags))
  icon: git
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/labbuildr-scripts.git
    branch: labbuildr_2020
- name: labbuildr-concourse-tasks
  tags: ((tags))
  icon: git
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/labbuildr-concourse-tasks.git
    branch: master

jobs:

- name: clone-node
  plan:
  - in_parallel:
    - get: one-time-trigger
      trigger: true
      tags: ((tags))
    - get: dps-automation-image
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))    
  - task: clone-node
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/clone-node.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.SQL_SINGLE_NODE.VMNAME))
      LABBUILDR_VM_MEMORY: 8192
      LABBUILDR_VM_CPU: 2
      LABBUILDR_VM_TEMPLATE: ((LABBUILDR.LAB1.SQL_SINGLE_NODE.TEMPLATE))
- name: generate-scripts-iso
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
      - clone-node
      trigger: true      
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
    - get: labbuildr-scripts
      tags: ((tags))   
  - task: generate-and-connect-cdrom
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/generate-scripts-iso.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.SQL_SINGLE_NODE.VMNAME))
      LABBUILDR_DEVICE: cdrom-3000
      LABBUILDR_SCRIPTS:
        - node
        - SQL
- name: diconnect-scripts-iso
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
      - generate-scripts-iso       
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags)) 
  - task: disconnect-cdrom
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/disconnect-scripts-iso.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.SQL_SINGLE_NODE.VMNAME))
      LABBUILDR_DEVICE: cdrom-3000

- name: join-domain
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
      - clone-node
      - generate-scripts-iso
      trigger: true
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
  - task: join-domain
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/domainjoin.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.SQL_SINGLE_NODE.VMNAME))
      LABBUILDR_VM_IP: ((LABBUILDR.LAB1.SUBNET)).((LABBUILDR.LAB1.SQL_SINGLE_NODE.IP))
      LABBUILDR_SCRIPTS:
        - node
        - SQL
      ADDON_FEATURES: "RSAT-ADDS, RSAT-ADDS-TOOLS, AS-HTTP-Activation, NET-Framework-45-Features"  

- name: unjoin-domain
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
      - join-domain
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
  - task: unjoin-domain
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/unjoin.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.SQL_SINGLE_NODE.VMNAME))
      LABBUILDR_DCNODE: ((LABBUILDR.LAB1.DCNODE.NAME))
 
- name: setup-sql
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
      - join-domain 
      trigger: true       
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags)) 
  - task: install-sql
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/configure-sqlnode.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.SQL_SINGLE_NODE.VMNAME))
      LABBUILDR_SCRIPTS:
        - node
        - SQL
      LABBUILDR_SQL_ISO: ((LABBUILDR.LAB1.SQLSERVER2019_ISO))

- name: delete-sqlnode
  plan:
  - in_parallel:
    - get: dps-automation-image
      tags: ((tags))
      passed:
      - clone-node
      trigger: false       
    - get: labbuildr-concourse-tasks
      tags: ((tags))    
  - task: delete-node
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/delete-node.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.SQL_SINGLE_NODE.VMNAME))