vsphere_env: &vsphere_env
  GOVC_INSECURE: ((GOVC.INSECURE))
  GOVC_PASSWORD: ((GOVC.PASSWORD))
  GOVC_URL: ((GOVC.URL))
  GOVC_USERNAME: ((GOVC.USERNAME))
  GOVC_RESOURCE_POOL: ((GOVC.RESOURCE_POOL))
  GOVC_DATASTORE: ((GOVC.DATASTORE)) 
  GOVC_DATACENTER: ((GOVC.DATACENTER)) 
  GOVC_NETWORK: ((GOVC.NETWORK))
  LABBUILDR_RESOURCE_POOL: ((LABBUILDR.LAB1.RESOURCE_POOL))
  LABBUILDR_DATASTORE: ((LABBUILDR.LAB1.DATASTORE)) 
  LABBUILDR_DATACENTER: ((LABBUILDR.LAB1.DATACENTER))
  LABBUILDR_NETWORK: ((LABBUILDR.LAB1.NETWORK))
  LABBUILDR_SUBNET: ((LABBUILDR.LAB1.SUBNET))
  LABBUILDR_GATEWAY: ((LABBUILDR.LAB1.GATEWAY))
  LABBUILDR_NETMASK: ((LABBUILDR.LAB1.NETMASK))
  LABBUILDR_FQDN: ((LABBUILDR.LAB1.FQDN))
  LABBUILDR_DNS: ((LABBUILDR.LAB1.DNS))
  LABBUILDR_VM_FOLDER: ((LABBUILDR.LAB1.VM_FOLDER))
  LABBUILDR_TIMEZONE: ((LABBUILDR.LAB1.TIMEZONE))
  LABBUILDR_LANGUAGE_TAG: ((LABBUILDR.LAB1.LANGUAGE_TAG))
  LABBUILDR_LOGINUSER: ((LABBUILDR.LAB1.WINDOWS_LOGINUSER))
  LABBUILDR_DEBUG: ((LABBUILDR.LAB1.DEBUG))
  LABBUILDR_VM_IPATH: ((LABBUILDR.LAB1.VM_FOLDER))/((LABBUILDR.LAB1.EXCHANGE_NODE.VMNAME))
  LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.EXCHANGE_NODE.VMNAME))
  GUEST_SCRIPT_DIR: ((LABBUILDR.GUEST_SCRIPT_DIR))
  NODE_SCRIPT_DIR: ((LABBUILDR.GUEST_SCRIPT_DIR))/((LABBUILDR.NODE_SCRIPT_DIR))
  SCENARIO_SCRIPT_DIR: ((LABBUILDR.GUEST_SCRIPT_DIR))/((LABBUILDR.SCENARIO_SCRIPT_DIR))

s3_env: &s3_env
  access_key_id: ((((foundation))/s3_access_key_id))
  endpoint:  ((((foundation))/s3_endpoint))
  region_name: ((((foundation))/s3_region_name))
  secret_access_key: ((((foundation))/s3_secret_access_key))

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
   
resources:
- name: one-time-trigger
  icon: calendar-clock
  tags: ((tags))      
  type: time
  source:
    interval: 999999h

- name: dps-automation-image
  icon: docker
  type: docker-image
  source:
    repository: bottkars/dps-automation-image
    tag: 0.3.12

- name: labbuildr-scripts
  tags: ((tags))
  icon: git
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/labbuildr-scripts.git
    branch: labbuildr_2020
- name: labbuildr-concourse-tasks
  tags: ((tags))
  icon: git
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/labbuildr-concourse-tasks.git
    branch: master
- name: netframework
  type: s3
  icon: folder-move
  source:
    <<: *s3_env
    bucket: swdist
    regexp: netframework/ndp(.*)-x86-x64-allos-enu.exe

- name: ucmaruntime
  type: s3
  icon: folder-move
  source:
    <<: *s3_env
    bucket: swdist
    regexp: ucmaruntime/UcmaRuntimeSetup-(.*).exe
- name: vcredist11
  type: s3
  icon: folder-move
  source:
    <<: *s3_env
    bucket: swdist
    regexp: vcredist/vcredist_x64-(11\..*).exe
- name: vcredist12
  type: s3
  icon: folder-move
  source:
    <<: *s3_env
    bucket: swdist
    regexp: vcredist/vcredist_x64-(12\..*).exe  


jobs:
- name: clone-node
  plan:
  - in_parallel:
    - get: one-time-trigger
      trigger: true
      tags: ((tags))
    - get: dps-automation-image
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))    
  - task: clone-node
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/clone-node.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
    params:
      <<: *vsphere_env
      LABBUILDR_VM_MEMORY: 8192
      LABBUILDR_VM_CPU: 2
      LABBUILDR_VM_TEMPLATE: ((LABBUILDR.LAB1.EXCHANGE_NODE.TEMPLATE))
- name: generate-scripts-iso
  plan:
  - in_parallel:
    - get: dps-automation-image
    - get: one-time-trigger
      passed:
      - clone-node
      trigger: true      
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
    - get: labbuildr-scripts
      tags: ((tags))   
  - task: generate-and-connect-cdrom
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/generate-scripts-iso.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_DEVICE: cdrom-3000
      LABBUILDR_SCRIPTS:
        - node
        - EXCHANGE
- name: diconnect-scripts-iso
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
      - generate-scripts-iso       
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags)) 
  - task: disconnect-cdrom
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/disconnect-scripts-iso.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
    params:
      <<: *vsphere_env
      LABBUILDR_DEVICE: cdrom-3000

- name: join-domain
  plan:
  - in_parallel:
    - get: dps-automation-image
    - get: one-time-trigger
      passed:
#      - clone-node
      - generate-scripts-iso
      trigger: true
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
  - task: join-domain
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/domainjoin.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_VM_IP: ((LABBUILDR.LAB1.SUBNET)).((LABBUILDR.LAB1.EXCHANGE_NODE.IP))
      LABBUILDR_SCRIPTS:
        - node
        - E2019
      #ADDON_FEATURES: "RSAT-ADDS, RSAT-ADDS-TOOLS, AS-HTTP-Activation, NET-Framework-45-Features"  
      ADDON_FEATURES: "Server-Media-Foundation, NET-Framework-45-Features, RPC-over-HTTP-proxy, RSAT-Clustering, RSAT-Clustering-CmdInterface, RSAT-Clustering-Mgmt, RSAT-Clustering-PowerShell, WAS-Process-Model, Web-Asp-Net45, Web-Basic-Auth, Web-Client-Auth, Web-Digest-Auth, Web-Dir-Browsing, Web-Dyn-Compression, Web-Http-Errors, Web-Http-Logging, Web-Http-Redirect, Web-Http-Tracing, Web-ISAPI-Ext, Web-ISAPI-Filter, Web-Lgcy-Mgmt-Console, Web-Metabase, Web-Mgmt-Console, Web-Mgmt-Service, Web-Net-Ext45, Web-Request-Monitor, Web-Server, Web-Stat-Compression, Web-Static-Content, Web-Windows-Auth, Web-WMI, Windows-Identity-Foundation, RSAT-ADDS"
- name: unjoin-domain
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
      - join-domain
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
  - task: unjoin-domain
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/unjoin.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_DCNODE: ((LABBUILDR.LAB1.DCNODE.NAME))
 
- name: setup-exchange-node
  plan:
  - in_parallel:
    - get: dps-automation-image
    - get: one-time-trigger
      passed:
      - join-domain 
      trigger: true       
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
  - task: setup-exchange-node
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/configure-exchangenode.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_SCRIPTS:
        - node
        - EXCHANGE
      LABBUILDR_EXCHANGE_ISO: ((LABBUILDR.LAB1.EXCHANGESERVER2019_ISO))
      LABBUILDR_EXCHANGE_CU: ((LABBUILDR.LAB1.EXCHANGESERVER2019_CU))

- name: deploy-exchange-prereqs
  plan:
  - in_parallel:
    - get: dps-automation-image
    - get: one-time-trigger
      passed:
      - setup-exchange-node
      trigger: true       
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
    - get: netframework
      tags: ((tags))
    - get: ucmaruntime
      tags: ((tags)) 
    - get: vcredist11
      tags: ((tags))  
    - get: vcredist12
      tags: ((tags))  
  - task: install-exchange-prereqs
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/deploy-exchange-prereqs.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_SCRIPTS:
        - node
        - EXCHANGE
      LABBUILDR_EXCHANGE_ISO: ((LABBUILDR.LAB1.EXCHANGESERVER2019_ISO))
      LABBUILDR_EXCHANGE_CU: ((LABBUILDR.LAB1.EXCHANGESERVER2019_CU))


- name: deploy-exchange
  plan:
  - in_parallel:
    - get: dps-automation-image
    - get: one-time-trigger
      passed:
      - deploy-exchange-prereqs
      trigger: true       
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
  - task: install-exchange
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/deploy-exchange.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_SCRIPTS:
        - node
        - EXCHANGE
      LABBUILDR_EXCHANGE_ISO: ((LABBUILDR.LAB1.EXCHANGESERVER2019_ISO))
      LABBUILDR_EXCHANGE_CU: ((LABBUILDR.LAB1.EXCHANGESERVER2019_CU))

- name: create-dag-exchange
  plan:
  - in_parallel:
    - get: dps-automation-image
    - get: one-time-trigger
      passed:
      - deploy-exchange
      trigger: false      
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
  - task: create-dag
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/create-dag.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_SCRIPTS:
        - node
        - EXCHANGE
      LABBUILDR_EXCHANGE_ISO: ((LABBUILDR.LAB1.EXCHANGESERVER2019_ISO))
      LABBUILDR_EXCHANGE_CU: ((LABBUILDR.LAB1.EXCHANGESERVER2019_CU))

- name: delete-exchangenode
  plan:
  - in_parallel:
    - get: dps-automation-image
      tags: ((tags))
      passed:
      - clone-node
      trigger: false       
    - get: labbuildr-concourse-tasks
      tags: ((tags))    
  - task: delete-node
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/delete-node.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
    params:
      <<: *vsphere_env
