vsphere_env: &vsphere_env
  GOVC_INSECURE: ((GOVC.INSECURE))
  GOVC_PASSWORD: ((GOVC.PASSWORD))
  GOVC_URL: ((GOVC.URL))
  GOVC_USERNAME: ((GOVC.USERNAME))
  GOVC_RESOURCE_POOL: ((GOVC.RESOURCE_POOL))
  GOVC_DATASTORE: ((GOVC.DATASTORE)) 
  GOVC_DATACENTER: ((GOVC.DATACENTER)) 
  GOVC_NETWORK: ((GOVC.NETWORK))
  LABBUILDR_RESOURCE_POOL: ((LABBUILDR.LAB1.RESOURCE_POOL))
  LABBUILDR_DATASTORE: ((LABBUILDR.LAB1.DATASTORE)) 
  LABBUILDR_DATACENTER: ((LABBUILDR.LAB1.DATACENTER))
  LABBUILDR_NETWORK: ((LABBUILDR.LAB1.NETWORK))
  LABBUILDR_SUBNET: ((LABBUILDR.LAB1.SUBNET))
  LABBUILDR_GATEWAY: ((LABBUILDR.LAB1.GATEWAY))
  LABBUILDR_NETMASK: ((LABBUILDR.LAB1.NETMASK))
  LABBUILDR_FQDN: ((LABBUILDR.LAB1.FQDN))
  LABBUILDR_DNS: ((LABBUILDR.LAB1.DNS))
  LABBUILDR_VM_FOLDER: ((LABBUILDR.LAB1.VM_FOLDER))
  LABBUILDR_TIMEZONE: ((LABBUILDR.LAB1.TIMEZONE))
  LABBUILDR_LANGUAGE_TAG: ((LABBUILDR.LAB1.LANGUAGE_TAG))
  LABBUILDR_LOGINUSER: ((LABBUILDR.LAB1.WINDOWS_LOGINUSER))

  
s3_env: &s3_env
  access_key_id: ((((foundation))/s3_access_key_id))
  endpoint:  ((((foundation))/s3_endpoint))
  region_name: ((((foundation))/s3_region_name))
  secret_access_key: ((((foundation))/s3_secret_access_key))

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
   
resources:
- name: one-time-trigger
  icon: calendar-clock
  tags: ((tags))      
  type: time
  source:
    interval: 999999h
- name: dps-automation-image
  icon: docker
  type: docker-image
  source:
    repository: harbor.pks.home.labbuildr.com/bottkars/dps-automation-image
    ca_certs:
    - domain: harbor.pks.home.labbuildr.com
      cert: ((pksdemo/pks_cert.ca))  

- name: labbuildr-scripts
  tags: ((tags))
  icon: git
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/labbuildr-scripts.git
    branch: labbuildr_2020
    private_key: ((git_read.private_key))

- name: labbuildr-concourse-tasks
  tags: ((tags))
  icon: git
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/labbuildr-concourse-tasks.git
    branch: master
    private_key: ((git_read.private_key))


jobs:
- name: clone-node
  plan:
  - in_parallel:
    - get: one-time-trigger
      trigger: true
      tags: ((tags))
    - get: dps-automation-image
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))    
  - task: clone-node
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/clone-node.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: dcnode
      LABBUILDR_VM_MEMORY: 4096
      LABBUILDR_VM_CPU: 2
      LABBUILDR_VM_TEMPLATE: ((LABBUILDR.LAB1.DCNODE.TEMPLATE))
- name: generate-scripts-iso
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
      - clone-node
      trigger: true      
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
    - get: labbuildr-scripts
      tags: ((tags))   
  - task: generate-and-connect-cdrom
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/generate-scripts-iso.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.DCNODE.VMNAME))
      LABBUILDR_DEVICE: cdrom-3000
      LABBUILDR_SCRIPTS:
        - node
        - dcnode
- name: diconnect-scripts-iso
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
#      - generate-scripts-iso       
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags)) 
  - task: disconnect-cdrom
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/disconnect-scripts-iso.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: ((LABBUILDR.LAB1.DCNODE.VMNAME))
      LABBUILDR_DEVICE: cdrom-3000
- name: configure-dc
  plan:
  - in_parallel:
    - get: dps-automation-image
      passed:
      - clone-node
      - generate-scripts-iso       
      trigger: true       
      tags: ((tags))        
    - get: labbuildr-concourse-tasks
      tags: ((tags))
    - get: labbuildr-scripts
      tags: ((tags))   
  - task: configure-node
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/configure-dcnode.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
      labbuildr-scripts: labbuildr-scripts
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: dcnode
      LABBUILDR_SCRIPTS:
        - node
        - dcnode

- name: delete-dc
  plan:
  - in_parallel:
    - get: dps-automation-image
      tags: ((tags))
      passed:
      - clone-node
      trigger: false       
    - get: labbuildr-concourse-tasks
      tags: ((tags))    
  - task: delete-node
    tags: ((tags))
    image: dps-automation-image
    file: labbuildr-concourse-tasks/vsphere/tasks/delete-node.yml
    input_mapping:
      labbuildr-concourse-tasks: labbuildr-concourse-tasks
    params:
      <<: *vsphere_env
      LABBUILDR_VM_NAME: dcnode